//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.29 at 09:18:23 AM CEST 
//
package im.bci.jb3.backend.legacy;

import java.util.List;

public class LegacyBoard {

    private String timezone;
    private List<LegacyPost> posts;
    private String site;

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public List<LegacyPost> getPosts() {
        return posts;
    }

    public void setPosts(List<LegacyPost> posts) {
        this.posts = posts;
    }

    public String getSite() {
        return site;
    }

    public void setSite(String site) {
        this.site = site;
    }

}
